services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: forza4_server
    ports:
      - "8080:8080"
    networks:
      - forza4_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: forza4_client
    depends_on:
      - server
    networks:
      - forza4_network
    stdin_open: true
    tty: true

networks:
  forza4_network:
    driver: bridge